import { Position } from './positionsModel';

export const positions: Position[] = [
  {
    title: 'Software Engineer',
    requirements: '3+ years experience in Java and Spring Framework',
    company: {
      name: 'Facebook',
      description: 'Social media and technology company',
      website: 'https://www.facebook.com/',
      location: 'Menlo Park, CA',
    },
    applicationDate: '2022-01-05',
    status: 'inProcess',
    contact: {
      name: 'John Doe',
      email: 'john.doe@facebook.com',
      phoneNumber: '555-1234',
    },
  },
  {
    title: 'Software Developer',
    company: {
      name: 'Tesla',
      description: 'Electric vehicle and clean energy company',
      website: 'https://www.tesla.com/',
      location: 'Palo Alto, CA',
    },
    applicationDate: '2022-02-01',
    status: 'applied',
  },
  {
    title: 'Senior UI Engineer',
    requirements: '5+ years experience in React and Redux',
    company: {
      name: 'Netflix',
      description: 'Streaming entertainment service',
      website: 'https://www.netflix.com/',
      location: 'Los Gatos, CA',
    },
    applicationDate: '2022-03-15',
    status: 'followUp',
    contact: {
      name: 'Jane Smith',
      email: 'jane.smith@netflix.com',
      phoneNumber: '555-5678',
    },
  },
  {
    title: 'Cloud Solutions Architect',
    requirements: '10+ years experience in cloud infrastructure design and implementation',
    company: {
      name: 'IBM',
      description: 'Technology and consulting company',
      website: 'https://www.ibm.com/',
      location: 'Armonk, NY',
    },
    applicationDate: '2022-04-10',
    status: 'noReply',
  },
  {
    title: 'Backend Engineer',
    requirements: '3+ years experience in Python and Django',
    company: {
      name: 'Twitter',
      description: 'Social media and technology company',
      website: 'https://www.twitter.com/',
      location: 'San Francisco, CA',
    },
    applicationDate: '2022-05-20',
    status: 'rejected',
    contact: {
      name: 'Adam Lee',
      email: 'adam.lee@twitter.com',
    },
  },
  {
    title: 'Software Engineer',
    company: {
      name: 'Salesforce',
      description: 'Customer relationship management software company',
      website: 'https://www.salesforce.com/',
      location: 'San Francisco, CA',
    },
    applicationDate: '2022-06-01',
    status: 'inProcess',
  },
  {
    title: 'Software Engineer',
    requirements: '3+ years experience in Java and Spring Framework',
    company: {
      name: 'Uber',
      description: 'Ride-hailing and transportation network company',
      website: 'https://www.uber.com/',
      location: 'San Francisco, CA, USA',
    },
    applicationDate: '2022-03-01',
    status: 'inProcess',
    contact: {
      name: 'Jane Doe',
      email: 'jane.doe@uber.com',
      phoneNumber: '555-5678',
    },
  },
  {
    title: 'Product Manager',
    requirements: '5+ years experience in product management',
    company: {
      name: 'Airbnb',
      description: 'Online marketplace for arranging or offering lodging, primarily homestays, or tourism experiences',
      website: 'https://www.airbnb.com/',
      location: 'San Francisco, CA, USA',
    },
    applicationDate: '2022-02-15',
    status: 'noReply',
    contact: {
      name: 'Bob Smith',
      email: 'bob.smith@airbnb.com',
      phoneNumber: '555-7890',
    },
  },
  {
    title: 'Frontend Developer',
    requirements: '2+ years experience in React and JavaScript',
    company: {
      name: 'Snapchat',
      description: 'Multimedia messaging app used globally',
      website: 'https://www.snapchat.com/',
      location: 'Los Angeles, CA, USA',
    },
    applicationDate: '2022-01-10',
    status: 'rejected',
  },
  {
    title: 'Marketing Manager',
    requirements: '7+ years experience in marketing and advertising',
    company: {
      name: 'Dropbox',
      description: 'File hosting service',
      website: 'https://www.dropbox.com/',
      location: 'San Francisco, CA, USA',
    },
    applicationDate: '2022-02-01',
    status: 'followUp',
    contact: {
      name: 'Sarah Johnson',
      email: 'sarah.johnson@dropbox.com',
      phoneNumber: '555-4321',
    },
  },
  {
    title: 'Senior Software Engineer',
    requirements: '5+ years of experience in backend development with Java or Python',
    company: {
      name: 'Zoom',
      description: 'Video communications company',
      website: 'https://zoom.us/',
      location: 'San Jose, CA, USA',
    },
    applicationDate: '2022-04-01',
    status: 'applied',
  },
  {
    title: 'Product Designer',
    requirements: '3+ years of experience in UX/UI design and a strong portfolio of work',
    company: {
      name: 'Square',
      description: 'Financial services and mobile payment company',
      website: 'https://squareup.com/',
      location: 'San Francisco, CA, USA',
    },
    applicationDate: '2022-03-15',
    status: 'followUp',
    contact: {
      name: 'Emily Chen',
      email: 'emily.chen@squareup.com',
      phoneNumber: '555-1234',
    },
  },
  {
    title: 'Senior Product Manager',
    requirements: '7+ years of experience in product management with a strong track record of shipping successful products',
    company: {
      name: 'PayPal',
      description: 'Online payments and financial services company',
      website: 'https://www.paypal.com/',
      location: 'San Jose, CA, USA',
    },
    applicationDate: '2022-02-28',
    status: 'inProcess',
    contact: {
      name: 'Michael Lee',
      email: 'michael.lee@paypal.com',
      phoneNumber: '555-5678',
    },
  },
  {
    title: 'Product Manager',
    requirements: '5+ years of experience in product management',
    company: {
      name: 'Google',
      description: 'Technology company specializing in internet-related services and products',
      website: 'https://www.google.com/',
      location: 'Mountain View, CA, USA',
    },
    applicationDate: '2022-03-15',
    status: 'followUp',
    contact: {
      name: 'Jane Doe',
      email: 'jane.doe@google.com',
      phoneNumber: '555-5678',
    },
  },
  {
    title: 'Software Development Engineer',
    requirements: "Bachelor's degree in Computer Science or related field",
    company: {
      name: 'Amazon',
      description: 'Online retail giant and cloud computing provider',
      website: 'https://www.amazon.com/',
      location: 'Seattle, WA, USA',
    },
    applicationDate: '2022-04-27',
    status: 'inProcess',
    contact: {
      name: 'John Smith',
      email: 'john.smith@amazon.com',
      phoneNumber: '555-1234',
    },
  },
  {
    title: 'Full Stack Developer',
    requirements: 'Proficient in Javascript, React, and Node.js',
    company: {
      name: 'Github',
      description: 'Web-based hosting service for version control of software',
      website: 'https://github.com/',
      location: 'San Francisco, CA',
    },
    applicationDate: '2023-04-10',
    status: 'applied',
    contact: {
      name: 'Jane Smith',
      email: 'jane.smith@github.com',
      phoneNumber: '555-5678',
    },
  },
  {
    title: 'Product Manager',
    requirements: 'Experience with user research and data analysis',
    company: {
      name: 'Reddit',
      description: 'Social news aggregation and discussion website',
      website: 'https://www.reddit.com/',
      location: 'San Francisco, CA',
    },
    applicationDate: '2023-03-15',
    status: 'applied',
    contact: {
      name: 'Bob Johnson',
      email: 'bob.johnson@reddit.com',
      phoneNumber: '555-9012',
    },
  },
  {
    title: 'Research Scientist',
    requirements: 'PhD in computer science or related field',
    company: {
      name: 'OpenAI',
      description: 'Research organization dedicated to advancing AI in a safe and beneficial way',
      website: 'https://openai.com/',
      location: 'San Francisco, CA',
    },
    applicationDate: '2023-02-20',
    status: 'rejected',
    contact: {
      name: 'Alex Lee',
      email: 'alex.lee@openai.com',
      phoneNumber: '555-3456',
    },
  },
  {
    title: 'Software Engineer',
    requirements: 'Experience with C++ and computer vision',
    company: {
      name: 'Apple',
      description: 'Consumer electronics and software company',
      website: 'https://www.apple.com/',
      location: 'Cupertino, CA',
    },
    applicationDate: '2023-01-25',
    status: 'inProcess',
    contact: {
      name: 'Emily Chen',
      email: 'emily.chen@apple.com',
      phoneNumber: '555-7890',
    },
  },
  {
    title: 'Data Scientist',
    requirements: 'Experience with machine learning and data analysis',
    company: {
      name: 'Microsoft',
      description: 'Technology company specializing in software, hardware, and services',
      website: 'https://www.microsoft.com/',
      location: 'Redmond, WA',
    },
    applicationDate: '2022-12-30',
    status: 'inProcess',
    contact: {
      name: 'David Kim',
      email: 'david.kim@microsoft.com',
      phoneNumber: '555-2345',
    },
  },
];
